In [1]:
import numpy as np

In [2]:
a = np.array([[2, 0, 8, 0],
              [0, 1, 0, 0],
              [0, 7, 1, 0],
              [0, 0, 3, 1]])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12],
              [13,14,15,16]])

np.matmul(a, b)

array([[ 74,  84,  94, 104],
       [  5,   6,   7,   8],
       [ 44,  52,  60,  68],
       [ 40,  44,  48,  52]])

In [3]:
import numpy as np

def blocked_matrix_multiply(A, B, block_size):
  m, n = A.shape
  n, p = B.shape
  C = np.zeros((m, p))

  for i in range(0, m, block_size):
    for j in range(0, p, block_size):
      for k in range(0, n, block_size):
        # Multiplica submatrizes usando a técnica de blocagem
        C[i:i+block_size, j:j+block_size] += np.dot(A[i:i+block_size, k:k+block_size], B[k:k+block_size, j:j+block_size])

  return C

blocked_matrix_multiply(a,b,2)

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [9]:
import numpy as np

def blocked_matrix_multiply(A, B, block_size):
  m, n = A.shape
  n, p = B.shape
  C = np.zeros((m, p))

  for i in range(0, m, block_size):
    for j in range(0, p, block_size):
      for k in range(0, n, block_size):
        # Multiplica submatrizes usando a técnica de blocagem
        C[i:i+block_size, j:j+block_size] += matrix_mul1(A[i:i+block_size, k:k+block_size],B[k:k+block_size, j:j+block_size]) 
  return C

blocked_matrix_multiply(a,b,2)

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [7]:
def blocked_matrix_multiply_b(A, B, block_size_i, block_size_k, block_size_j):
  m, n = A.shape
  n, p = B.shape
  C = np.zeros((m, p))

  for block_i in range(0, m, block_size_i):
    for block_j in range(0, p, block_size_j):
      for block_k in range(0, n, block_size_k):
        # Multiplica submatrizes usando a técnica de blocagem
        # C[i:i+block_size, j:j+block_size_j] += matrix_mul1(A[i:i+block_size, k:k+block_size],B[k:k+block_size, j:j+block_size_j]) 
        C[block_i:block_i+block_size_i, block_j:block_j+block_size_j] += np.dot(A[block_i:block_i+block_size_i, block_k:block_k+block_size_k],B[block_k:block_k+block_size_k, block_j:block_j+block_size_j])
  return C

blocked_matrix_multiply_b(a,b,2,1,2)

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [3]:
def matrix_mul1(A,B):
  m , n = A.shape
  C = np.zeros((m,n))

  for i in range(n):
    for j in range(n):
      for k in range(n):
        # print(f'C[{i},{j}] += A[{i},{k}] * B[{k},{j}]')
        C[i,j] += A[i,k] * B[k,j]

  return C

matrix_mul1(a,b)

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [10]:
def matrix_mul2(A,B):
  m , n = A.shape
  C = np.zeros((m,n))

  for i in range(n):
    for k in range(n):
      for j in range(n):
        print(f'C[{i},{j}] += A[{i},{k}] * B[{k},{j}]')
        C[i,j] += A[i,k] * B[k,j]

  return C

matrix_mul2(a,b)

C[0,0] += A[0,0] * B[0,0]
C[0,1] += A[0,0] * B[0,1]
C[0,2] += A[0,0] * B[0,2]
C[0,3] += A[0,0] * B[0,3]
C[0,0] += A[0,1] * B[1,0]
C[0,1] += A[0,1] * B[1,1]
C[0,2] += A[0,1] * B[1,2]
C[0,3] += A[0,1] * B[1,3]
C[0,0] += A[0,2] * B[2,0]
C[0,1] += A[0,2] * B[2,1]
C[0,2] += A[0,2] * B[2,2]
C[0,3] += A[0,2] * B[2,3]
C[0,0] += A[0,3] * B[3,0]
C[0,1] += A[0,3] * B[3,1]
C[0,2] += A[0,3] * B[3,2]
C[0,3] += A[0,3] * B[3,3]
C[1,0] += A[1,0] * B[0,0]
C[1,1] += A[1,0] * B[0,1]
C[1,2] += A[1,0] * B[0,2]
C[1,3] += A[1,0] * B[0,3]
C[1,0] += A[1,1] * B[1,0]
C[1,1] += A[1,1] * B[1,1]
C[1,2] += A[1,1] * B[1,2]
C[1,3] += A[1,1] * B[1,3]
C[1,0] += A[1,2] * B[2,0]
C[1,1] += A[1,2] * B[2,1]
C[1,2] += A[1,2] * B[2,2]
C[1,3] += A[1,2] * B[2,3]
C[1,0] += A[1,3] * B[3,0]
C[1,1] += A[1,3] * B[3,1]
C[1,2] += A[1,3] * B[3,2]
C[1,3] += A[1,3] * B[3,3]
C[2,0] += A[2,0] * B[0,0]
C[2,1] += A[2,0] * B[0,1]
C[2,2] += A[2,0] * B[0,2]
C[2,3] += A[2,0] * B[0,3]
C[2,0] += A[2,1] * B[1,0]
C[2,1] += A[2,1] * B[1,1]
C[2,2] += A[

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [33]:
def mat_mul3(A, B, block_size):
  n = a.shape[0]
  C = np.zeros((n,n))
  for block_i in range(0, n, block_size):
    for block_j in range(0, n, block_size):
      for block_k in range(0, n, block_size):
        for i in range(block_size):
          for k in range(block_size):
            for j in range(block_size):
              print(f'C[{block_i + i}, {block_j + j}] += A[{block_i + i},{block_k + k}] * B[{block_k+k},{block_j + j}]')
              C[block_i + i, block_j + j] += A[block_i + i,block_k + k] * B[block_k+k,block_j + j]
  return C

mat_mul3(a,b,1)

C[0, 0] += A[0,0] * B[0,0]
C[0, 0] += A[0,1] * B[1,0]
C[0, 0] += A[0,2] * B[2,0]
C[0, 0] += A[0,3] * B[3,0]
C[0, 1] += A[0,0] * B[0,1]
C[0, 1] += A[0,1] * B[1,1]
C[0, 1] += A[0,2] * B[2,1]
C[0, 1] += A[0,3] * B[3,1]
C[0, 2] += A[0,0] * B[0,2]
C[0, 2] += A[0,1] * B[1,2]
C[0, 2] += A[0,2] * B[2,2]
C[0, 2] += A[0,3] * B[3,2]
C[0, 3] += A[0,0] * B[0,3]
C[0, 3] += A[0,1] * B[1,3]
C[0, 3] += A[0,2] * B[2,3]
C[0, 3] += A[0,3] * B[3,3]
C[1, 0] += A[1,0] * B[0,0]
C[1, 0] += A[1,1] * B[1,0]
C[1, 0] += A[1,2] * B[2,0]
C[1, 0] += A[1,3] * B[3,0]
C[1, 1] += A[1,0] * B[0,1]
C[1, 1] += A[1,1] * B[1,1]
C[1, 1] += A[1,2] * B[2,1]
C[1, 1] += A[1,3] * B[3,1]
C[1, 2] += A[1,0] * B[0,2]
C[1, 2] += A[1,1] * B[1,2]
C[1, 2] += A[1,2] * B[2,2]
C[1, 2] += A[1,3] * B[3,2]
C[1, 3] += A[1,0] * B[0,3]
C[1, 3] += A[1,1] * B[1,3]
C[1, 3] += A[1,2] * B[2,3]
C[1, 3] += A[1,3] * B[3,3]
C[2, 0] += A[2,0] * B[0,0]
C[2, 0] += A[2,1] * B[1,0]
C[2, 0] += A[2,2] * B[2,0]
C[2, 0] += A[2,3] * B[3,0]
C[2, 1] += A[2,0] * B[0,1]
C

array([[ 74.,  84.,  94., 104.],
       [  5.,   6.,   7.,   8.],
       [ 44.,  52.,  60.,  68.],
       [ 40.,  44.,  48.,  52.]])

In [21]:
for i in range(0, 4, 2):
  print(i)

0
2
